version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:latest
    steps:
      - checkout
      - run: mvn compile
  test:
    docker:
      - image: circleci/openjdk:latest
    steps:
      - checkout
      - run: mvn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
